### ISSUE TITLE
Optionality

### ISSUE THREAD

**Issue by Wolfr** [mono-company/bedrock#165]
When you start a new project, Bedrock is sometimes too heavy.

I think we can solve this by making more things optional, and disabling them by default.

Bedrock should start with very little: just jade, html, css and js compilation.

Through configs you can manipulate what you want to use.

This way we don't need separate projects like https://github.com/mono-company/bedrock-mini .

* [x] #163 If there are no icons at all, do not show the icon listing in the prototype
* [x] #164 If there are no components at all, do not show the component listing in the prototype
* [x] #151 Style guide optional
* [x] #142 Colors optional

**Comment by thomastuts** [comment]
For the icons & colors overview, we'll need to move the relevant doc files to the `core/` folder instead. This is because they are two docs that are pretty much auto-generated by Bedrock, and having them in the `core/` folder will ensure that they are always available, and always at the same path.

This means that these files will not be editable on a project-by-project basis though. Is that an issue?

**Comment by thomastuts** [comment]
That being said, you _could_ also just delete the `icons` and `colors` files in the docs folder, and you'd end up with the same result...

**Comment by Wolfr** [comment]
I think it's nice to be able to edit them on a per project level, e.g. to hardcode some icon documentation that doesn't follow the logic of the other.

Like I mentioned on Slack it's just that if you have no icons folder, Bedrock gives an error.
